% This code was generated using ADiGator version 1.3
% ©2010-2014 Matthew J. Weinstein and Anil V. Rao
% ADiGator may be obtained at https://sourceforge.net/projects/adigator/ 
% Contact: mweinstein@ufl.edu
% Bugs/suggestions may be reported to the sourceforge forums
%                    DISCLAIMER
% ADiGator is a general-purpose software distributed under the GNU General
% Public License version 3.0. While the software is distributed with the
% hope that it will be useful, both the software and generated code are
% provided 'AS IS' with NO WARRANTIES OF ANY KIND and no merchantability
% or fitness for any purpose or application.

function output = goddardRocketContinuousADiGatorGrd(input)
global ADiGator_goddardRocketContinuousADiGatorGrd
if isempty(ADiGator_goddardRocketContinuousADiGatorGrd); ADiGator_LoadData(); end
Gator1Data = ADiGator_goddardRocketContinuousADiGatorGrd.goddardRocketContinuousADiGatorGrd.Gator1Data;
% ADiGator Start Derivative Computations
%User Line: %--------------------------------------%
%User Line: % Begin File:  goddardRocketContinuous %
%User Line: %--------------------------------------%
auxdata = input.auxdata;
%User Line: auxdata = input.auxdata;
t.dV = input.phase(1).time.dV;
t.f = input.phase(1).time.f;
%User Line: t = input.phase(1).time;
x.dV = input.phase(1).state.dV;
x.f = input.phase(1).state.f;
%User Line: x = input.phase(1).state;
T.dV = input.phase(1).control.dV;
T.f = input.phase(1).control.f;
%User Line: T = input.phase(1).control;
h.dV = x.dV(:,1);
h.f = x.f(:,1);
%User Line: h = x(:,1);
v.dV = x.dV(:,2);
v.f = x.f(:,2);
%User Line: v = x(:,2);
m.dV = x.dV(:,3);
m.f = x.f(:,3);
%User Line: m = x(:,3);
cada1f1dV = 2.*v.f.^(2-1).*v.dV;
cada1f1 = v.f.^2;
cada1f2dV = auxdata.dragk.*cada1f1dV;
cada1f2 = auxdata.dragk*cada1f1;
cada1f3dV = -h.dV;
cada1f3 = uminus(h.f);
cada1f4dV = cada1f3dV./auxdata.H;
cada1f4 = cada1f3/auxdata.H;
cada1f5dV = exp(cada1f4).*cada1f4dV;
cada1f5 = exp(cada1f4);
cada1td1 = zeros(size(cada1f2dV,1),2);
cada1td1(:,2) = cada1f5.*cada1f2dV;
cada1td1(:,1) = cada1td1(:,1) + cada1f2.*cada1f5dV;
D.dV = cada1td1;
D.f = cada1f2.*cada1f5;
%User Line: D = auxdata.dragk.*(v.^2).*exp(-h/auxdata.H);
hdot.dV = v.dV; hdot.f = v.f;
%User Line: hdot = v;
cada1td1 = zeros(size(T.dV,1),3);
cada1td1(:,3) = T.dV;
cada1td1(:,Gator1Data.Index1) = cada1td1(:,Gator1Data.Index1) + -D.dV;
cada1f1dV = cada1td1;
cada1f1 = T.f - D.f;
cada1tf1 = m.f(:,Gator1Data.Index2);
cada1td1 = zeros(size(cada1f1dV,1),4);
cada1td1(:,Gator1Data.Index3) = cada1f1dV./cada1tf1;
cada1td1(:,3) = cada1td1(:,3) + -cada1f1./m.f.^2.*m.dV;
cada1f2dV = cada1td1;
cada1f2 = cada1f1./m.f;
cada1f3 = size(t.f);
cada1f4 = ones(cada1f3);
cada1f5 = auxdata.g0*cada1f4;
vdot.dV = cada1f2dV;
vdot.f = cada1f2 - cada1f5;
%User Line: vdot = (T-D)./m-auxdata.g0*ones(size(t));
cada1f1dV = -T.dV;
cada1f1 = uminus(T.f);
mdot.dV = cada1f1dV./auxdata.c;
mdot.f = cada1f1/auxdata.c;
%User Line: mdot = -T./auxdata.c;
cada1td1 = zeros(size(hdot.f,1),6);
cada1td1(:,2) = hdot.dV;
cada1td1(:,Gator1Data.Index4) = vdot.dV;
cada1td1(:,6) = mdot.dV;
cada1f1dV = cada1td1;
cada1f1 = [hdot.f vdot.f mdot.f];
output(1).dynamics.dV = cada1f1dV;
output(1).dynamics.f = cada1f1;
%User Line: output(1).dynamics = [hdot, vdot, mdot];
t.dV = input.phase(2).time.dV;
t.f = input.phase(2).time.f;
%User Line: t = input.phase(2).time;
x.dV = input.phase(2).state.dV;
x.f = input.phase(2).state.f;
%User Line: x = input.phase(2).state;
T.dV = input.phase(2).control.dV;
T.f = input.phase(2).control.f;
%User Line: T = input.phase(2).control;
h.dV = x.dV(:,1);
h.f = x.f(:,1);
%User Line: h = x(:,1);
v.dV = x.dV(:,2);
v.f = x.f(:,2);
%User Line: v = x(:,2);
m.dV = x.dV(:,3);
m.f = x.f(:,3);
%User Line: m = x(:,3);
cada1f1dV = 2.*v.f.^(2-1).*v.dV;
cada1f1 = v.f.^2;
cada1f2dV = auxdata.dragk.*cada1f1dV;
cada1f2 = auxdata.dragk*cada1f1;
cada1f3dV = -h.dV;
cada1f3 = uminus(h.f);
cada1f4dV = cada1f3dV./auxdata.H;
cada1f4 = cada1f3/auxdata.H;
cada1f5dV = exp(cada1f4).*cada1f4dV;
cada1f5 = exp(cada1f4);
cada1td1 = zeros(size(cada1f2dV,1),2);
cada1td1(:,2) = cada1f5.*cada1f2dV;
cada1td1(:,1) = cada1td1(:,1) + cada1f2.*cada1f5dV;
D.dV = cada1td1;
D.f = cada1f2.*cada1f5;
%User Line: D = auxdata.dragk.*(v.^2).*exp(-h/auxdata.H);
hdot.dV = v.dV; hdot.f = v.f;
%User Line: hdot = v;
cada1td1 = zeros(size(T.dV,1),3);
cada1td1(:,3) = T.dV;
cada1td1(:,Gator1Data.Index5) = cada1td1(:,Gator1Data.Index5) + -D.dV;
cada1f1dV = cada1td1;
cada1f1 = T.f - D.f;
cada1tf1 = m.f(:,Gator1Data.Index6);
cada1td1 = zeros(size(cada1f1dV,1),4);
cada1td1(:,Gator1Data.Index7) = cada1f1dV./cada1tf1;
cada1td1(:,3) = cada1td1(:,3) + -cada1f1./m.f.^2.*m.dV;
cada1f2dV = cada1td1;
cada1f2 = cada1f1./m.f;
cada1f3 = size(t.f);
cada1f4 = ones(cada1f3);
cada1f5 = auxdata.g0*cada1f4;
vdot.dV = cada1f2dV;
vdot.f = cada1f2 - cada1f5;
%User Line: vdot = (T-D)./m-auxdata.g0*ones(size(t));
cada1f1dV = -T.dV;
cada1f1 = uminus(T.f);
mdot.dV = cada1f1dV./auxdata.c;
mdot.f = cada1f1/auxdata.c;
%User Line: mdot = -T./auxdata.c;
cada1td1 = zeros(size(hdot.f,1),6);
cada1td1(:,2) = hdot.dV;
cada1td1(:,Gator1Data.Index8) = vdot.dV;
cada1td1(:,6) = mdot.dV;
cada1f1dV = cada1td1;
cada1f1 = [hdot.f vdot.f mdot.f];
output(2).dynamics.dV = cada1f1dV;
output(2).dynamics.f = cada1f1;
%User Line: output(2).dynamics = [hdot, vdot, mdot];
voverc.dV = v.dV./auxdata.c;
voverc.f = v.f/auxdata.c;
%User Line: voverc = v/auxdata.c;
xmg.dV = auxdata.g0.*m.dV;
xmg.f = m.f*auxdata.g0;
%User Line: xmg = m*auxdata.g0;
cada1f1 = auxdata.c^2;
cada1f2 = size(t.f);
cada1f3 = ones(cada1f2);
cada1f4dV = voverc.dV;
cada1f4 = cada1f3 + voverc.f;
cada1f5dV = cada1f1.*cada1f4dV;
cada1f5 = cada1f1*cada1f4;
cada1f6 = auxdata.H*auxdata.g0;
cada1f7dV = cada1f5dV./cada1f6;
cada1f7 = cada1f5/cada1f6;
cada1f8 = size(t.f);
cada1f9 = ones(cada1f8);
cada1f10dV = cada1f7dV;
cada1f10 = cada1f7 - cada1f9;
cada1f11dV = -2./voverc.f.^2.*voverc.dV;
cada1f11 = 2./voverc.f;
cada1td1 = cada1f10dV;
cada1td1 = cada1td1 + -cada1f11dV;
term1.dV = cada1td1;
term1.f = cada1f10 - cada1f11;
%User Line: term1 = (auxdata.c^2).*(ones(size(t))+voverc)./(auxdata.H*auxdata.g0)-ones(size(t))-2./voverc;
cada1f1 = size(t.f);
cada1f2 = ones(cada1f1);
cada1f3dV = -4./voverc.f.^2.*voverc.dV;
cada1f3 = 4./voverc.f;
cada1f4dV = cada1f3dV;
cada1f4 = cada1f2 + cada1f3;
cada1f5dV = 2.*voverc.f.^(2-1).*voverc.dV;
cada1f5 = voverc.f.^2;
cada1f6dV = -2./cada1f5.^2.*cada1f5dV;
cada1f6 = 2./cada1f5;
cada1td1 = cada1f4dV;
cada1td1 = cada1td1 + cada1f6dV;
cada1f7dV = cada1td1;
cada1f7 = cada1f4 + cada1f6;
cada1td1 = zeros(size(xmg.dV,1),2);
cada1td1(:,2) = xmg.dV./cada1f7;
cada1td1(:,1) = cada1td1(:,1) + -xmg.f./cada1f7.^2.*cada1f7dV;
term2.dV = cada1td1;
term2.f = xmg.f./cada1f7;
%User Line: term2 = xmg./(ones(size(t))+4./voverc+2./(voverc.^2));
cada1td1 = zeros(size(T.dV,1),3);
cada1td1(:,3) = T.dV;
cada1td1(:,Gator1Data.Index9) = cada1td1(:,Gator1Data.Index9) + -D.dV;
cada1f1dV = cada1td1;
cada1f1 = T.f - D.f;
cada1td1 = zeros(size(cada1f1dV,1),4);
cada1td1(:,Gator1Data.Index10) = cada1f1dV;
cada1td1(:,3) = cada1td1(:,3) + -xmg.dV;
cada1f2dV = cada1td1;
cada1f2 = cada1f1 - xmg.f;
cada1td1 = zeros(size(term1.dV,1),2);
cada1td1(:,1) = term2.f.*term1.dV;
cada1tf1 = term1.f(:,Gator1Data.Index11);
cada1td1 = cada1td1 + cada1tf1.*term2.dV;
cada1f3dV = cada1td1;
cada1f3 = term1.f.*term2.f;
cada1td1 = cada1f2dV;
cada1td1(:,Gator1Data.Index12) = cada1td1(:,Gator1Data.Index12) + -cada1f3dV;
cada1f4dV = cada1td1;
cada1f4 = cada1f2 - cada1f3;
output(2).path.dV = cada1f4dV;
output(2).path.f = cada1f4;
%User Line: output(2).path = T-D-xmg-term1.*term2;
t.dV = input.phase(3).time.dV;
t.f = input.phase(3).time.f;
%User Line: t = input.phase(3).time;
x.dV = input.phase(3).state.dV;
x.f = input.phase(3).state.f;
%User Line: x = input.phase(3).state;
T.dV = input.phase(3).control.dV;
T.f = input.phase(3).control.f;
%User Line: T = input.phase(3).control;
h.dV = x.dV(:,1);
h.f = x.f(:,1);
%User Line: h = x(:,1);
v.dV = x.dV(:,2);
v.f = x.f(:,2);
%User Line: v = x(:,2);
m.dV = x.dV(:,3);
m.f = x.f(:,3);
%User Line: m = x(:,3);
cada1f1dV = 2.*v.f.^(2-1).*v.dV;
cada1f1 = v.f.^2;
cada1f2dV = auxdata.dragk.*cada1f1dV;
cada1f2 = auxdata.dragk*cada1f1;
cada1f3dV = -h.dV;
cada1f3 = uminus(h.f);
cada1f4dV = cada1f3dV./auxdata.H;
cada1f4 = cada1f3/auxdata.H;
cada1f5dV = exp(cada1f4).*cada1f4dV;
cada1f5 = exp(cada1f4);
cada1td1 = zeros(size(cada1f2dV,1),2);
cada1td1(:,2) = cada1f5.*cada1f2dV;
cada1td1(:,1) = cada1td1(:,1) + cada1f2.*cada1f5dV;
D.dV = cada1td1;
D.f = cada1f2.*cada1f5;
%User Line: D = auxdata.dragk.*(v.^2).*exp(-h/auxdata.H);
hdot.dV = v.dV; hdot.f = v.f;
%User Line: hdot = v;
cada1td1 = zeros(size(T.dV,1),3);
cada1td1(:,3) = T.dV;
cada1td1(:,Gator1Data.Index13) = cada1td1(:,Gator1Data.Index13) + -D.dV;
cada1f1dV = cada1td1;
cada1f1 = T.f - D.f;
cada1tf1 = m.f(:,Gator1Data.Index14);
cada1td1 = zeros(size(cada1f1dV,1),4);
cada1td1(:,Gator1Data.Index15) = cada1f1dV./cada1tf1;
cada1td1(:,3) = cada1td1(:,3) + -cada1f1./m.f.^2.*m.dV;
cada1f2dV = cada1td1;
cada1f2 = cada1f1./m.f;
cada1f3 = size(t.f);
cada1f4 = ones(cada1f3);
cada1f5 = auxdata.g0*cada1f4;
vdot.dV = cada1f2dV;
vdot.f = cada1f2 - cada1f5;
%User Line: vdot = (T-D)./m-auxdata.g0*ones(size(t));
cada1f1dV = -T.dV;
cada1f1 = uminus(T.f);
mdot.dV = cada1f1dV./auxdata.c;
mdot.f = cada1f1/auxdata.c;
%User Line: mdot = -T./auxdata.c;
cada1td1 = zeros(size(hdot.f,1),6);
cada1td1(:,2) = hdot.dV;
cada1td1(:,Gator1Data.Index16) = vdot.dV;
cada1td1(:,6) = mdot.dV;
cada1f1dV = cada1td1;
cada1f1 = [hdot.f vdot.f mdot.f];
output(3).dynamics.dV = cada1f1dV;
output(3).dynamics.f = cada1f1;
%User Line: output(3).dynamics = [hdot, vdot, mdot];
%User Line: %------------------------------------%
%User Line: % End File:  goddardRocketContinuous %
%User Line: %------------------------------------%
output(1).dynamics.dV_size = [3,5];
output(1).dynamics.dV_location = Gator1Data.Index17;
output(2).dynamics.dV_size = [3,5];
output(2).dynamics.dV_location = Gator1Data.Index18;
output(2).path.dV_size = 5;
output(2).path.dV_location = Gator1Data.Index19;
output(3).dynamics.dV_size = [3,5];
output(3).dynamics.dV_location = Gator1Data.Index20;
end


function ADiGator_LoadData()
global ADiGator_goddardRocketContinuousADiGatorGrd
ADiGator_goddardRocketContinuousADiGatorGrd = load('goddardRocketContinuousADiGatorGrd.mat');
return
end